### ISSUE TITLE
Relocate vendor and resources folders on windows?

### ISSUE THREAD

**Issue by fraserdale** [asticode/go-astilectron-bundler#14] opened 2018-01-31 01:34 UTC
When running a compiled app on windows the following folder are created with the relevant contents. 
'vendor' and 'resources'
Is there a way that I can stop these being created in the same directory as the one that the app is executed in and stored elsewhere eg in the appdata folder

**Comment by asticode** [comment] 2018-03-31 12:04
Duplicate of https://github.com/asticode/go-astilectron/issues/78, closing this issue

**Closed by asticode** 2018-03-31 12:04 UTC
Labels: enhancement
