### ISSUE TITLE
Bundler on Windows creates console window.

### ISSUE THREAD

**Issue by FloThinksPi** [asticode/go-astilectron-bundler#16] opened 2018-03-05 20:40 UTC
When Opening the Gui of the Demo Project(https://github.com/asticode/go-astilectron-demo) on windows, there is also a empty CLI besides the Electron GUI.

So i suspect the `-ldflags -H=windowsgui` flag is not set properly in
https://github.com/asticode/go-astilectron-bundler/blob/c9aa756170b8ee1a40f9f3640d34e8f6fbc80f6b/bundler.go#L435-L437

Or does the `bundler.json` needs any adaption here ?

Best Regards 
Florian :)

**Comment by asticode** [comment] 2018-03-06 08:23
@FloThinksPi are you working on Windows 10 or on a lower version? Which version of Go are you using?

**Comment by FloThinksPi** [comment] 2018-03-07 10:28
Hi @asticode I am on Windows 10 and Go 1.10

**Comment by asticode** [comment] 2018-03-31 12:01
@FloThinksPi Could you test on Go 1.10.1 ? I've tested it with Windows 10 and it's working properly.

**Comment by SebaArriagada** [comment] 2018-04-08 20:05
I'm seeing the same behavior on Windows 10 with Go version go1.10.1 windows/amd64

**Comment by asticode** [comment] 2018-04-09 08:25
ha, so you're building a windows binary from a windows machine?

I'll try that.

**Comment by SebaArriagada** [comment] 2018-04-09 14:52
Yes, exactly.

**Comment by asticode** [comment] 2018-04-09 15:00
ok, can anyone test building a windows binary on a linux machine like I did and say whether it works with Go 1.10.1 and Windows 10?

**Comment by SebaArriagada** [comment] 2018-04-09 18:08
I tested it building on linux with go version go1.10.1 linux/amd64 and running it on Windows 10 and the problem persists

**Comment by asticode** [comment] 2018-04-10 07:40
Damn, that's a bummer.

A few questions:
- are you using any kind of cygwin-based terminals? If so, which ones?
- which type of console window appears? a windows one or something else?
- could attach a screenshot here so that I can see exactly?

**Comment by FloThinksPi** [comment] 2018-04-10 08:10
I compiled one on Linux for Windows and will try if this occurs when i am back from Work.
I Use git for Windows in cygwin but the shell that opened was a windows cmd. I will make a scrrenshot also when i am back home.

**Comment by SebaArriagada** [comment] 2018-04-10 13:41
In my case I used a virtual machine created just for this test, running Linux Mint, to build the Windows executable. Here is a screenshot of how it looks like:

![win10](https://user-images.githubusercontent.com/5461092/38560038-126faebc-3cab-11e8-8d56-b99a946966b1.png)

**Comment by SebaArriagada** [comment] 2018-04-10 18:51
Yes, I used the default demo project. Just added the `environments` option in the bundler.json file in order to build it for windows in the linux machine. When building in windows I didn't change anything. In both cases the empty console appears and the window title is `Electron`

**Comment by asticode** [comment] 2018-04-11 07:16
@SebaArriagada could you try the following:

- tell me what is the [electron version](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L23) and the [astilectron version](https://github.com/asticode/go-astilectron/blob/master/astilectron.go#L22) used currently in the `go-astilectron` project
- could you make sure all the `astilectron` projects are up to date (`go-astilectron`, `go-astilectron-bundler`, `go-astilectron-bootstrap`, `go-astilectron-demo`)
- could you `go install` the bundler again once all the projects are up to date
- could you build the demo project and tell me whether you're still experiencing the issue

I want to check whether the problem is caused by an older version of electron or astilectron used.

**Comment by SebaArriagada** [comment] 2018-04-11 14:05
The versions are:
```
        VersionAstilectron      = "0.20.0"
        VersionElectron         = "1.8.1"
```
I managed to get rid of the empty console but I don't know the reason behind it. In the first attemps I did a `git clone` of the demo repo instead of a `go get` as the readme file says (my bad, I'm sorry). I'm pretty new in Go, and I'm very used to just clone a repo. Do you know why that append? Is this still a bug?
Thanks for your time.

**Comment by asticode** [comment] 2018-04-11 14:16
No worries about the `git clone`: if you do it, others do it, therefore the project needs to be compatible with it :)
The fact that you managed to get rid of the empty console is very good news. I don't know whether this is linked to the Electron version as I think it is.

@FloThinksPi could you:
- make sure all the `astilectron` projects (`go-astilectron`, `go-astilectron-bundler`, `go-astilectron-bootstrap`, `go-astilectron-demo`) are up to date
- `go install` the bundler
- build your project again
- and tell us whether you see the empty console?

**Comment by SebaArriagada** [comment] 2018-04-11 14:39
One think I forgot to point out is that I didn't update anything from the tests I did before. The test that work and the ones that not, were built with the same `astilectron` project's versions  (`go-astilectron`, `go-astilectron-bundler` and `go-astilectron-bootstrap`). The only difference was the demo project.

**Comment by asticode** [comment] 2018-04-18 08:00
hey guys, could you check out the last answer of [this issue](https://github.com/golang/go/issues/24232) and see if that helps in any way?

**Comment by sebaap** [comment] 2018-04-19 12:52
hey @asticode, seems like the last answer is about how to reproduce the problem. I managed to solve it by using `go get` in linux, but in windows I haven't been able to get rid of the empty console.
Seems to be a go problem, so I gave up with go and decided to go back to javascript.
Anyway, if you need me to test something just let me know.

**Comment by asticode** [comment] 2018-05-28 08:06
Hey guys,

Seems like the issue is indeed in *GO* and will be fixed in the next version: https://github.com/golang/go/issues/24232#issuecomment-392309327. Seems like it will also be backported to 1.10.

I'll close this issue for now, but feel free to reopen it if the problem is still there even after upgrading GO.

Cheers

**Closed by asticode** 2018-05-28 08:06 UTC
Labels: bug
